src/Entity/Answer.php
<?php

namespace App\Entity;

use App\Repository\AnswerRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=AnswerRepository::class)
 */
class Answer
{
    public const STATUS_NEED_APPROVAL = 'need_approval';
    public const STATUS_NEED_SPAM = 'spam';
    public const STATUS_NEED_APPROVED = 'approved';

    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="integer")
     */
    private $votes = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="answers")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=15)
     */
    private $status = self::STATUS_NEED_APPROVAL;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): self
    {
        $this->votes = $votes;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function getQuestionText(): string
    {
        if(!$this->getQuestion()){
            return '';
        }

        return (string) $this->getQuestion()->getQuestion();
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function upVote(): self
    {
        $this->votes++;

        return $this;
    }

    public function downVote(): self
    {
        $this->votes--;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = $this->getVotes() >= 0 ? '+ ' : '- ';

        return sprintf('%s %d', $prefix, abs($this->getVotes()));
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        if(!in_array($status,[self::STATUS_NEED_APPROVAL, self::STATUS_NEED_APPROVED, self::STATUS_NEED_SPAM])){
            throw new \InvalidArgumentException(sprintf('Invalid status "%s"', $status));
        }
        $this->status = $status;

        return $this;
    }

    public function isApproved(): bool
    {
        return $this->status === self::STATUS_NEED_APPROVED;
    }
}

src/Controller/AnswerController.php
<?php

namespace App\Controller;

use App\Entity\Answer;
use App\Repository\AnswerRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class AnswerController extends BaseController
{
    /**
     * Api to handle the answer vote count
     *
     * @Route("/answers/{id}/vote/{direction<up|down>}", methods="POST")
     *
     * @param Answer $answer The answer
     * @param string $direction The type of vote up or down
     * @param EntityManagerInterface $entityManager The entity manager interface
     * @param LoggerInterface $logger The Logger interface
     *
     * @return JsonResponse Return the number of votes
     * @IsGranted("IS_AUTHENTICATED_REMEMBERED")
     */

    public function answerVote(Answer $answer, string $direction, EntityManagerInterface $entityManager, LoggerInterface $logger): JsonResponse
    {
        $logger->info('{user} is voting in {answer}!', [
            'answer' => $answer->getId(),
            'user'=> $this->getUser()->getEmail()
        ]);
        if ($direction === 'up') {
            $answer->upVote();
        } else {
            $answer->downVote();
        }

        $entityManager->flush();

        return $this->json(['votes' => $answer->getVotesString()]);
    }

    /**
     * Return the most popular questions
     *
     * @Route("/answers/popular", name="app_popular_answers")
     *
     * @param AnswerRepository $repository
     * @param Request $request
     * @return Response
     * @throws \Doctrine\ORM\Query\QueryException
     */

    public function popularAnswers(AnswerRepository $repository, Request $request) : Response
    {
        $popularAnswers = $repository->findMostPopular($request->query->get('q'));

        return $this->render(
            'answers/popularAnswers.html.twig',
            ['answers' => $popularAnswers]
        );
    }


}

templates/answers/_answer.html.twig
<li class="mb-2">
    {% if showQuestion|default(false) %}
        <a href="{{ path('app_question_show',{
            slug:answer.question.slug
        }) }}"
           class="mb-1 link-secondary"
        ><strong>Question : </strong>
            {{ answer.questionText|u.truncate(80,'...') }}
        </a>
    {% endif %}
    <div class="row mt-2">
        <div class="col-1">
            <img src="{{ asset('images/tisha.png') }}" width="50" height="50">
        </div>
        <div class="col-9">
            {{ answer.content|parse_markdown }}
            <p>-- {{ answer.username }}</p>
        </div>
        <div class="col-2 text-end">
            <small>{{ answer.createdAt|ago }}</small>
            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <div class="vote-arrows js-vote-arrows" style="min-width: 120px;">
                    <button class="vote-up" href="#" data-direction="up" data-answer={{ answer.id }}><i
                                class="far fa-arrow-alt-circle-up"></i></button>
                    <button class="vote-down" href="#" data-direction="down" data-answer="{{ answer.id }}"><i
                                class="far fa-arrow-alt-circle-down"></i></button>
                    <span><span class="js-vote-total">{{ answer.votesString }}</span></span>
                </div>
            {% endif %}
        </div>
    </div>
</li>

templates/answers/popularAnswers.html.twig
{% extends 'base.html.twig' %}

{% block title %} Popular Answers {% endblock %}

{% block body %}
    <div class="container my-md-4">
        <div class="d-flex justify-content-between">
            <h1>Most Popular Answers</h1>
            <form action="{{ path('app_popular_answers') }}">
                <input
                    type="search"
                    name="q"
                    value="{{ app.request.query.get('q') }}"
                    class="form-control"
                    placeholder="Search..."
                    aria-label="Search"
                >
            </form>
        </div>
        <ul class="list-unstyled">
            {% for answer in answers %}
                {{ include('answers/_answer.html.twig', {
                    showQuestion: true
                }) }}
            {% endfor %}
        </ul>
    </div>
{% endblock %}